version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        networks:
            - votprx
        ports:
            - 20000:80
        depends_on:
            - voting
    voting:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - votdb
            - votprx
            - votrds
        env_file:
            - .env
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        networks:
            - votdb
        environment:
            MYSQL_ROOT_PASSWORD: 123qweASD
            MYSQL_USER: voting
            MYSQL_DATABASE: voting
            MYSQL_PASSWORD: voting
    redis:
        image: redis:latest
        networks:
            - votrds

            
networks:
    votprx:
    votdb:
    votrds:
