version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        networks:
            - votprx
        ports:
            - 20000:80
        depends_on:
            - voting
        links:
            - fluentd
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: nginx.access

    voting:
        image: dkr-31:voting
        networks:
            - votdb
            - votprx
            - votrds
        env_file:
            - .env
        depends_on:
            - mysql
        links:
            - fluentd
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: voting

    mysql:
        image: mysql:5.7
        networks:
            - votdb
        environment:
            MYSQL_ROOT_PASSWORD: 123qweASD
            MYSQL_USER: voting
            MYSQL_DATABASE: voting
            MYSQL_PASSWORD: voting
        links:
            - fluentd
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: mysql

    redis:
        image: redis:latest
        networks:
            - votrds
        links:
            - fluentd
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: redis

    fluentd:
        build: ./fluentd
        volumes: 
            - ./fluentd/conf:/fluentd/etc
        links:
            - "elasticsearch"
        ports:
            - "24224:24224"
            - "24224:24224/udp"
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        expose:
            - "9200"
        ports:
            - "9200:9200"
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.0
        links:
            - "elasticsearch"
        ports:
            - "5601:5601"
            
networks:
    votprx:
    votdb:
    votrds:
